### ISSUE TITLE
 Failed loading pipeline component 'Retriever'. See the stacktrace above for more information.

### ISSUE THREAD

**Issue by Suhaib441** [deepset-ai/haystack-tutorials#138]
**Describe the issue**
Trying to launch the Rest-api with Milvusdocumentstore and dpr Retrieval but im not able to run the query endpoint. 
Im using a seperate script for indexing

While uploading my_pipeline.yml with python and launching pipeline.run(query) it works fine. but when im launching the Rest API the Query endpoint send this : 
 File "/opt/venv/lib/python3.10/site-packages/rest_api/controller/search.py", line 67, in _process_request
    result = pipeline.run(query=request.query, params=params, debug=request.debug)
AttributeError: 'NoneType' object has no attribute 'run'

**To Reproduce**
**pipeline.yml**  
components:
- name: MilvusDocumentStore
  params:
    embedding_dim: 384
    index: custom_index
  type: MilvusDocumentStore
- name: Retriever
  params:
    document_store: MilvusDocumentStore
    passage_embedding_model: sentence-transformers/all-MiniLM-L6-v2
    query_embedding_model: sentence-transformers/all-MiniLM-L6-v2
  type: DensePassageRetriever
- name: Reader
  params:
    model_name_or_path: deepset/roberta-base-squad2
  type: TransformersReader
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reader
version: 1.14.0

**My Docker-compse.yml for The Rest API** :

version: '3.5'
services:
  haystack-api:
    #build:
     # context: .
     # dockerfile: ./haystack.Dockerfile
    image: "deepset/haystack:cpu"
    volumes:
      - ./rest_api/rest_api/pipeline:/opt/pipelines
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - PIPELINE_YAML_PATH=/opt/pipelines/my_pipeline.yml
      - TOKENIZERS_PARALLELISM=false
      - HAYSTACK_TELEMETRY_ENABLED=false

 - Haystack Version [1.4]

**Additional context**
The Initialized send 200 with True, Maybe i have something missing in my docker-comopse or pipeline.yml but as i said the pipeline.yml works fine with a python script.

**Comment by JonathanLehner** [comment]
same problem for me

**Comment by JonathanLehner** [comment]
how to run it?

**Comment by JonathanLehner** [comment]
I am just trying to run the code as in the Github

**Comment by JonathanLehner** [comment]
@Suhaib441 it is not helpful to just close the issue without any comments
