### ISSUE TITLE
Tutorial 22 shows irrelevant results

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-tutorials#208]
As we noticed together with @bilgeyucel,
currently the [Tutorial 22](https://haystack.deepset.ai/tutorials/22_pipeline_with_promptnode) produces some irrelevant results,
possibly due to prompt truncation.

Since it has great importance, we should ensure that it produces good results.

**Comment by bilgeyucel** [comment]
There are two options here:
* Try another open source model with a larger context limit
    *  Should be runnable on Colab (or we can use HuggingFace Inference API but this requires a key)
* Update the dataset we're using by splitting files with a smaller window size

**Comment by TuanaCelik** [comment]
Thanks for spotting this ppl! Another option is to use one of the other datasets we have. We now have quite a few we can pick from on HF: presidents, pycon, seven wonders (current) and game of thrones.
