### ISSUE TITLE
tutorial 14 fails on nightly tests

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-tutorials#220]
The tutorial is working fine on colab with Haystack 1.18 and on main but fails on [nightly test](https://github.com/deepset-ai/haystack-tutorials/actions/runs/5502615310/jobs/10026990043#step:8:26)

**Comment by anakin87** [comment]
Hey @bilgeyucel!

`SklearnQueryClassifier` has been deprecated in https://github.com/deepset-ai/haystack/issues/5323.

I see two options for this tutorial:

- the `SklearnQueryClassifier` can stay in the tutorial until it is removed. 
- given that the same task can be done with `TransformersQueryClassifier`, remove it from the tutorial.

WDYT?

**Comment by bilgeyucel** [comment]
Hi @anakin87, thank you for doing this. We can already switch to `TransformersQueryClassifier` if there won't be a big difference in the tutorial flow. 
I opened a separate issue to handle this update https://github.com/deepset-ai/haystack-tutorials/issues/221
