### ISSUE TITLE
Update RAG tutorials

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-tutorials#228]
Hey @bilgeyucel - currently the only thing with RAG in the title is the tutorial that is out dated, while the tutorial with PromptNode is probably exactly what people are looking for. Could we think of a way to maybe make some wording or title updates to both to make sure that when people
Look for rag they find the new one.
We could even have the option of "hiding" the old tutorials or not indexing them, but I'll leave that up to you.

**Comment by bilgeyucel** [comment]
I opened a PR to mitigate this problem. If we think that the changes are not enough, I am happy to make a second iteration.
