### ISSUE TITLE
DPR inference

### ISSUE THREAD

**Issue by salbatarni** [deepset-ai/haystack-tutorials#234]
- How to use the DPR model I trained in inference?
- I am using other matrices, so how to get the similarity between a test query and passage?

**Comment by jdixosnd** [comment]
You can load trained DPR using `load` method
```reloaded_retriever = DensePassageRetriever.load(load_dir=save_dir, document_store=None)```
Found this code in,
https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/09_DPR_training.ipynb

Also, can you please elaborate your another query.

**Comment by salam020** [comment]
@jdixosnd 
I think you misunderstood
now I am done training a DPR model and I want to test it, how to do so? I am aware of the evaluation tutorial, however, the DPR data format is really different so I am unsure how to do it.

**Comment by bilgeyucel** [comment]
This issue is related to Haystack v1, closing it
Feel free to reopen this if you still have the issue
