### ISSUE TITLE
Unable to use "from haystack.document_stores import FAISSDocumentStore"

### ISSUE THREAD

**Issue by ashlytom** [deepset-ai/haystack-tutorials#238]
**Describe the issue**
Whenever i try to import 
from haystack.document_stores import FAISSDocumentStore
i get the following errors 
"""
ImportError: cannot import name 'MODEL_TO_ENCODING' from 'tiktoken.model' (C:\Users\25013529\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiktoken\model.py)
"""

**To Reproduce**
Run this
from haystack.document_stores import FAISSDocumentStore

**Expected behavior**
I expected the installation to be done and to start using the FAISSDocumentStore

**What environment did you try to run the tutorial on?:**
 - OS: Windows 10 Pro 
 - Browser [e.g. chrome, safari]: Chrome
 - Haystack Version 
faiss-cpu                     1.7.4
farm-haystack                 1.20.0

**Additional context**

**Comment by bilgeyucel** [comment]
Hi @ashlytom, according to [this stackoverflow entry](https://stackoverflow.com/questions/77088431/haystack-raises-cannot-import-name-model-to-encoding-from-tiktoken-model), this issue should be fixed with 1.20.1. Do you still encounter this issue?
