### ISSUE TITLE
New tutorial for: Hybrid Retrieval

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-tutorials#240]
**Describe the tutorial you would like to see here**
A tutorial to explain how to create a haystack pipeline with hybrid retrieval. 
* This tutorial should be easy to follow and showcase the advantages of hybrid retrieval over individual semantic search and keyword search. 
* It should be runnable as a python notebook and convertible to a python script 
* Dataset can be downloaded from Hugging Face Dataset. Example here: https://haystack.deepset.ai/tutorials/25_customizing_agent#creating-a-generative-qa-pipeline-tool

[x] I've checked the existing tutorials

**Comment by nickprock** [comment]
Hi @bilgeyucel 
can you assign it to me?
