### ISSUE TITLE
ModuleNotFoundError No module named 'haystack.reader'

### ISSUE THREAD

**Issue by chandru1003** [deepset-ai/haystack-tutorials#254]
**Describe the issue**

I encountered the following error while running the chatbot.py script:
```python
Exception has occurred: ModuleNotFoundError
No module named 'haystack.reader'
  File "C:\GITREPO\File-Based-Chatbot\chatbot.py", line 7, in <module>
    from haystack.reader.farm import FARMReader
ModuleNotFoundError: No module named 'haystack.reader'
```

## To Reproduce

Clone the repository: git clone https://github.com/chandru1003/File-Based-Chatbot.git
Run the script: python chatbot.py

**What environment did you try to run the tutorial on?:**
 - OS: [window 10 pro]
 - Processor [Intel core i3]
 - RAM : 4 GB
 - system type 64bit 
 - editor: VS code
 

Additional context

I installed  ```pip install farm-haystack``` and ```pip install haystack```

##  Screen Shot

![image](https://github.com/deepset-ai/haystack-tutorials/assets/55582956/e6fea7bb-2511-4fe6-9871-6c8c993e2508)

![image](https://github.com/deepset-ai/haystack-tutorials/assets/55582956/a2273985-70f5-419d-a6c9-1018036ba6ce)

**Comment by anakin87** [comment]
The right package was `farm-haystack` and I can't reproduce the issue.

Now we recommend switching to [Haystack 2.x](https://docs.haystack.deepset.ai/docs/migration).
