### ISSUE TITLE
Error when training DPR model on my own dataset (Tutorial 9)

### ISSUE THREAD

**Issue by ranieristyaa** [deepset-ai/haystack-tutorials#309]
**Describe the issue**
i am about to fine tune a DPR model on my own dataset. i could run the training process before with no error, last time i run it was like 1 week ago. but now when i am trying to run the training again with same data, same code, and same environment it keeps getting error like this:
![image](https://github.com/deepset-ai/haystack-tutorials/assets/75117691/ac434426-248e-445f-a9dc-85c1cf5bb599)

**To Reproduce**
here is my colab code: https://colab.research.google.com/drive/1bKR4cNkxQwJhmm_gXfhdgHNmKIsgvu-R?usp=sharing
and the data i am using:
[answersDPR.json](https://github.com/deepset-ai/haystack-tutorials/files/14691844/answersDPR.json)

**Expected behavior**
the code supposed to run correctly like this:
![image](https://github.com/deepset-ai/haystack-tutorials/assets/75117691/60ce0795-512f-498c-b949-830e23c620e0)

and the model should fine-tuned succesfully.

**What environment did you try to run the tutorial on?:**
 - OS: Windows 11
 - Browser : chrome
 - Haystack Version 1.x

**Comment by anakin87** [comment]
Probably something has changed in the latest versions of PyTorch.

I managed to fix the error with the following commands:

```python
import torch.distributed as dist
import os

os.environ['MASTER_ADDR'] = '127.0.0.1'
os.environ['MASTER_PORT'] = '29500'

dist.init_process_group("gloo", rank=0, world_size=1)
```

More information in the PyTorch docs: [here](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#basic-use-case) and [here](https://pytorch.org/tutorials/intermediate/dist_tuto.html).

**Comment by ranieristyaa** [comment]
it is fixed, thank you
