### ISSUE TITLE
Haystack v1.x tutorials tests failing

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-tutorials#326]
**Describe the issue**
Several tests in v1 tutorials are failing because in 1.26 we removed the `fetch_archive_from_http` utility function (used in 17 tutorials).

We should decide on a strategy to solve this problem.

**Comment by silvanocerza** [comment]
This should be solved by deepset-ai/haystack#7806, let's wait for tonight nightly to verify everything is working correctly and then close this.
