### ISSUE TITLE
Replace the occurrences of Multiplexer component with BranchJoiner

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-tutorials#336]
The Multiplexer component will be removed in 2.4 release, so the below resources need to be updated to showcase the use of BranchJoiner instead.

1. [37_Simplifying_Pipeline_Inputs_with_Multiplexer](https://github.com/deepset-ai/haystack-tutorials/blob/dcb384ebee58a8aade29f6a707d0169b51cf5fac/tutorials/37_Simplifying_Pipeline_Inputs_with_Multiplexer.ipynb#L9)
2. [ReadMe](https://github.com/deepset-ai/haystack-tutorials/blob/dcb384ebee58a8aade29f6a707d0169b51cf5fac/README.md?plain=1#L47) 
3. [index.toml](https://github.com/deepset-ai/haystack-tutorials/blob/dcb384ebee58a8aade29f6a707d0169b51cf5fac/index.toml#L404)

**Comment by bilgeyucel** [comment]
We deprecated the tutorial instead
