### ISSUE TITLE
Create a version of tutorial "Building Fallbacks to Websearch with Conditional Routing" using ChatGenerator

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-tutorials#350]
We need to better understand how complex and difficult to understand tutorials would get if we used ChatGenerator instead of the regular Generators. For that purpose, let's create a version of https://haystack.deepset.ai/tutorials/36_building_fallbacks_with_conditional_routing using ChatGenerator.

**Comment by julian-risch** [comment]
related to https://github.com/deepset-ai/haystack-tutorials/issues/349

**Comment by vblagoje** [comment]
Not as trivial for conversion as https://github.com/deepset-ai/haystack-tutorials/issues/349 - this one took me about 10 min to convert and test. But, imho, relatively easy. Here is the [notebook](https://colab.research.google.com/drive/1L9BxyUmGOf4EDOSq2bkONmxRz7dKHva9?usp=sharing)

cc @julian-risch @TuanaCelik
