### ISSUE TITLE
Document joiner tutorial - input prompt to LLM with no whitespaces and mixed contents

### ISSUE THREAD

**Issue by aleflabo** [deepset-ai/haystack-tutorials#362]
I'm looking at the input prompt to the LLM of the [tutorial about document joiner](https://docs.haystack.deepset.ai/docs/documentjoiner#additional-references), and the output prompt has lots of words with no whitespaces between them. Is the output of the LLM affected? Do you know how I can solve this issue? I tried using the ollama embedder, and the output had the same problem.
The documents used are the ones downloaded in the tutorial: one .txt, one .pdf and one .md 

![image](https://github.com/user-attachments/assets/d806b30e-a003-463a-809d-39a83ebf1034)

**Comment by anakin87** [comment]
This PDF is somewhat strange, so currently the only way to properly extract the text is via a custom `Converter`.

```python
from pypdf import PdfReader
from haystack import Document, default_to_dict, default_from_dict

class CustomConverter:
    def convert(self, reader: "PdfReader") -> Document:
        """Extract text from the PDF and return a Document object with the text content."""
        text = "\f".join(page.extract_text(extraction_mode="layout") for page in reader.pages)
        return Document(content=text)

    def to_dict(self):
        """Serialize the converter to a dictionary."""
        return default_to_dict(self)

    @classmethod
    def from_dict(cls, data):
        """Deserialize the converter from a dictionary."""
        return default_from_dict(cls, data)

pdf_converter = PyPDFToDocument(converter=CustomConverter())
```

I will do the following:
- use a better PDF in the tutorial
- investigate simpler ways for users to customize PDF conversion

**Comment by anakin87** [comment]
I'm closing this issue and moving the discussion of simpler ways for users to customize PDF conversion to https://github.com/deepset-ai/haystack/issues/8553
