### ISSUE TITLE
Colab button missing from tutorials on GitHub

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-tutorials#47]
**Describe the issue**
With PR https://github.com/deepset-ai/haystack-tutorials/pull/40 the Colab button is no more visible when looking at the tutorial files on GitHub. In my opinion, we should add them again.

Here is the old view with the button:
https://github.com/deepset-ai/haystack-tutorials/blob/1b592d5791e711489a6d25a4ff8f0a7160b174d1/tutorials/01_Basic_QA_Pipeline.ipynb

And the new one without the button:
https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/01_Basic_QA_Pipeline.ipynb

@TuanaCelik if we don't add the button linking to colab I'd assume that fewer users will try running the code.

As an alternative to adding the button, maybe we could at least add a link?

**Comment by TuanaCelik** [comment]
Hey @julian-risch  - This was taken out because we auto-generate a button on the website: https://haystack-home.vercel.app/tutorials/01_basic_qa_pipeline

So if we have it back in (without some preprocessing in markdown generation) it would show up twice. 

If you think it's important to have the button for the people who will run the tutorials via accessing them on GitHub we can make this a feature issue and do some edits to the `generate_mardowns.py` script to skip the button cell.

**Comment by julian-risch** [comment]
I think it would be nice to have the button also here on GitHub, yes. Otherwise, if somebody links to the tutorial on GitHub (https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/01_Basic_QA_Pipeline.ipynb) there is no button at all and no link in that file to colab.

**Comment by TuanaCelik** [comment]
@julian-risch - I've closed that PR as it won't be the way we go :) 
But I'll think about how we can do this alongside a download button. @bilgeyucel I might as for your help coming up with something nice that works for everyone here. Let's take this offline and I'll update the issue when we have some suggestions.

**Comment by TuanaCelik** [comment]
Hey @julian-risch I'm doing a clean up of the issues on haystack-tutorials. If it's ok I will close this one as we already made some changes based off of this conversation:
- easier spottable colab button on websits
- Download option
- Colab buttons for each tutorial on the readme here

And looking at any tutorial being run on Colab, things have started to look up in the past few weeks:
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/15802862/207058085-d0810be5-bfca-42e5-adc9-85a49fb1db86.png">
