### ISSUE TITLE
Tutorial 16 doesn't work

### ISSUE THREAD

**Issue by vblagoje** [deepset-ai/haystack-tutorials#48]
**Describe the issue**

I tried running the tutorial directly from Github https://colab.research.google.com/github/deepset-ai/haystack-tutorials/blob/main/tutorials/16_Document_Classifier_at_Index_Time.ipynb 

The tutorials fails with:

<img width="1123" alt="Screenshot 2022-10-24 at 16 39 00" src="https://user-images.githubusercontent.com/458335/197553224-4c6dc3fa-fec4-45b3-8e6f-a9bb1c249874.png">

**To Reproduce**

Click [here](https://colab.research.google.com/github/deepset-ai/haystack-tutorials/blob/main/tutorials/16_Document_Classifier_at_Index_Time.ipynb)

**Expected behavior**
Tutorial succeeds.

**What environment did you try to run the tutorial on?:**
Google Colab
**Additional context**

**Comment by TuanaCelik** [comment]
Hey @vblagoje  - I get this error with the [ocr] option enabled fyi
