### ISSUE TITLE
Titles and title formatting on Tutorials 19

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-tutorials#64]
@mayankjobanputra @bilgeyucel jfyi we noticed that the titles formats are off on this tutorial: https://haystack.deepset.ai/tutorials/19_text_to_image_search_pipeline_with_multimodal_retriever

So I'm creating this issue to fix it. I can create a PR tomorrow and add you as reviewer

**Comment by mayankjobanputra** [comment]
I just checked... Things are off on multiple tutorials. Let's talk more on this tomorrow :)
