### ISSUE TITLE
Fix formatting on all tutorials

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-tutorials#75]
Formatting of some tutorials is off. 

Some examples: 
![image](https://user-images.githubusercontent.com/25897116/203806950-ea3c6d08-3fb4-4454-b4bb-05e47ff096de.png)
![image](https://user-images.githubusercontent.com/25897116/203807044-98eb0002-622b-4dda-99c5-c6f816441e52.png)

This is a header issue, probably it will all be fixed by using the correct level of titles. Only h1 and h2 are possible for ToC. 

This issue is better to be fixed after PR #44 is ready and the new format for tutorials is settled.

**Comment by TuanaCelik** [comment]
@bilgeyucel I will assign this issue to you to keep track of. One PR regarding this was merged last week. Feel free to close this issue if that was the only related one.
