### ISSUE TITLE
02_Finetune_a_model_on_your_data.ipynb: A wrong file download location crash the process

### ISSUE THREAD

**Issue by goldyard** [deepset-ai/haystack-tutorials#83]
**Describe the issue**
[Fine-tuning a Model on Your Own Data](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/02_Finetune_a_model_on_your_data.ipynb)

Part 2: 
Downloading very small dataset to make tutorial faster (please use a bigger dataset for real use cases)
```python
s3_url = "https://s3.eu-central-1.amazonaws.com/deepset.ai-farm-qa/datasets/documents/squad_small.json.zip"
fetch_archive_from_http(url=s3_url, output_dir=doc_dir)
```

File download error cause the squad_small.json could not be downloaded.

**To Reproduce**
Just run with jupyter and cause error.

**Expected behavior**
Should execute without error.

**What environment did you try to run the tutorial on?:**
 - OS: Ubuntu 22.04 + miniconda + jupyter-lab
 - Browser: Chrome
 - Haystack Version: main stream

**Additional context**
should be changed to:

```python
s3_url = "https://s3.eu-central-1.amazonaws.com/deepset.ai-farm-qa/datasets/documents/squad_small.json.zip"
fetch_archive_from_http(url=s3_url, output_dir="data/temp")
!cp data/temp/*.json .
```

**Comment by bilgeyucel** [comment]
Hi @goldyard, I see that you can download the zip file to the `data/temp` directory and copy them to the current directory with `!cp data/temp/*.json .` . 
What's the exact error you get when you try to fetch the zip file without the `cp` command? This seems like it can be a read/write issue in the `doc_dir` you defined.

**Comment by goldyard** [comment]
When the previous download and the squad_small.json.zip downloaded into the same folder, the second download operation will failed since it find the folder has already exists. So the squad_small.json.zip download task will ignore and exit.

**Comment by bilgeyucel** [comment]
Hi @goldyard, what is the error message you get? When I want to rerun the cell with the code snippet you shared, I am only getting this:
```
INFO:haystack.utils.import_utils:Found data stored in 'data/tutorial2/squad_small'. Delete this first if you really want to fetch new data.
```
If this is the one you get, it is just a warning not to override your existing files. This log shouldn't interrupt your runtime or affect anything if you are following the tutorial without any changes.

**Comment by goldyard** [comment]
I'm not sure what happened, but it works on Colab is a good result anyway. Thanks for your kind response.
