### ISSUE TITLE
Upgrade torch to 1.13.0

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-tutorials#87]
**Describe the issue**
Let's upgrade to torch 1.13.0 (and to 1.13.1 as soon as it is released) to prepare for speed improvements coming with version 2.0.

@mayankjobanputra tracked changes between 1.13.1 and 2.0. It seems that the changes from there aren't big. If we upgrade to 1.13 now it will hopefully allow us to make the jump to 2.0 quickly.

**Additional context**

**Comment by mayankjobanputra** [comment]
In case someone is interested in reading further about torch-2.0 and torch-1.13,
Here is nice FAQ: https://pytorch.org/get-started/pytorch-2.0/#faqs

**Comment by julian-risch** [comment]
Sorry, let's track this in the Haystack repo instead: https://github.com/deepset-ai/haystack/issues/3683
