### ISSUE TITLE
Lab 16: Explain use of Elastic in Index section

### ISSUE THREAD

**Issue by rgstephens** [deepset-ai/haystack-tutorials#96]
**Describe the tutorial you would like to see here**
At [this](https://github.com/deepset-ai/haystack-tutorials/blob/main/markdowns/16_Document_Classifier_at_Index_Time.md#start-an-elasticsearch-server) point in the tutorial we state that we're going to start Elastic but not why we're doing this. What's the objective of this **Index** section of the lab?

[x] I've checked the existing tutorials

**Comment by TuanaCelik** [comment]
Thank you @rgstephens - we're updating the tutorials one by one. I'll keep this issue here until we get to this particular one 🙏🏽

**Comment by bilgeyucel** [comment]
[Tutorial 16](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/16_Document_Classifier_at_Index_Time.ipynb) uses Haystack 1.0 and we should write the 2.0 version of it. Closing this issue for the sake of #355
